# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d6c636c51b87c230b1018572c81de716b6386c54e67814765dbb059084c3e286496fbaa8444defe5f2689d5a61e89a367410ef0e6f09df9d40872beeaf89358

test:
  secret_key_base: d8990718620a7ffb9918ede887bde370567344ba0e3eaef33546c75d072c349f656a3efdb11136e5fe8b3e7f7b4e1790beb7417e255f7614ecc1b0320ac51f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
